package edu.dosw.sirha.services.observer;

import edu.dosw.sirha.model.ClassSession;
import edu.dosw.sirha.utils.AlertFactory;
import java.util.ArrayList;
import java.util.List;

/**
 * Observer that monitors class sessions for quota and capacity issues.
 * It generates alerts based on the events received from the class sessions.
 */
public class ClassQuotaObserver implements ClassSessionObserver {
    private List<Alert> alerts;
    private AlertFactory quotaAlertFactory;
    private AlertFactory capacityAlertFactory;

    /**
     * Constructor initializes the observer with empty alert list and alert factories.
     */
    public ClassQuotaObserver() {
        this.alerts = new ArrayList<>();
        this.quotaAlertFactory = AlertFactory.getFactory("quota");
        this.capacityAlertFactory = AlertFactory.getFactory("capacity");
    }

    /**
     * Updates the observer with a new event from a class session.
     * Depending on the event type, it creates and sends an appropriate alert.
     * @param classSession the class session that generated the event
     * @param eventType the type of event (e.g., "QUOTA_EXCEEDED", "STUDENT_ADDED")
     * @param data additional data related to the event
     */
    @Override
    public void update(ClassSession classSession, String eventType, Object data) {
        Alert alert = createAlert(classSession, eventType, data);
        if (alert != null) {
            alerts.add(alert);
            alert.send();
        }
    }

    /**
     * Creates an alert based on the event type and class session.
     * @param classSession the class session related to the alert
     * @param eventType the type of event triggering the alert
     * @param data additional data for the alert
     * @return the created alert, or null if an error occurred
     */
    private Alert createAlert(ClassSession classSession, String eventType, Object data) {
        try {
            if (eventType.contains("QUOTA")) {
                return quotaAlertFactory.createAlert(classSession, eventType, data);
            } else if (eventType.contains("STUDENT") || eventType.contains("CAPACITY")) {
                return capacityAlertFactory.createAlert(classSession, eventType, data);
            } else {
                return AlertFactory.getFactory("general").createAlert(classSession, eventType, data);
            }
        } catch (Exception e) {
            System.err.println("Error al crear la alerta: " + e.getMessage());
            return null;
        }
    }

    /**
     * Returns a copy of the list of alerts generated by this observer.
     * @return a list of alerts
     */
    public List<Alert> getAlerts() {
        return new ArrayList<>(alerts);
    }

    /**
     * Clears all alerts from the observer's list.
     */
    public void clearAlerts() {
        alerts.clear();
    }
}