spring.application.name=Backend_SIRHA_Romanos_2025-2

spring.mongodb.uri=mongodb+srv://admin:admin@sirha-db.wvkmubn.mongodb.net/?retryWrites=true&w=majority&appName=SIRHA-DB
spring.mongodb.database=sirha
