package edu.dosw.sirha.controller.dtos;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Data Transfer Object for group responses.
 * Contains the complete information of a group returned to the client.
 * This DTO follows the same pattern as PetitionResponseDTO, using flattened fields
 * for related entities rather than embedded objects, providing all necessary
 * information in a single, flat structure.
 */
@Data
@Schema(description = "Data transfer object for group responses containing complete group information")
public class GroupsResponseDTO {

    /**
     * Unique identifier of the group.
     * This is the primary key generated by the system when the group is created.
     */
    @Schema(
            description = "Unique identifier of the group",
            example = "group123"
    )
    private String groupId;

    /**
     * Name of the group.
     * This is the display name that identifies the group to users.
     */
    @Schema(
            description = "Name of the group",
            example = "Group A - Object Oriented Programming"
    )
    private String groupName;

    /**
     * Description or additional information about the group.
     * May contain details about the group's purpose, requirements, or special notes.
     */
    @Schema(
            description = "Description or additional information about the group",
            example = "Working group for the final project of Object Oriented Programming course"
    )
    private String description;

    // Professor information (flattened, following PetitionResponseDTO pattern)
    /**
     * Unique identifier of the professor assigned to this group.
     */
    @Schema(
            description = "Unique identifier of the professor assigned to the group",
            example = "prof123"
    )
    private String professorCode;

    /**
     * Full name of the professor assigned to this group.
     */
    @Schema(
            description = "Full name of the professor assigned to the group",
            example = "Dr. Maria Rodriguez Garcia"
    )
    private String professorName;

    /**
     * Email address of the professor assigned to this group.
     */
    @Schema(
            description = "Email address of the professor assigned to the group",
            example = "maria.rodriguez@escuelaing.edu.co"
    )
    private String professorEmail;

    /**
     * Document number of the professor assigned to this group.
     */
    @Schema(
            description = "Document number of the professor assigned to the group",
            example = "12345678"
    )
    private String professorDocument;

    // Subject information (flattened, following PetitionResponseDTO pattern)
    /**
     * Unique identifier of the subject this group belongs to.
     */
    @Schema(
            description = "Unique identifier of the subject this group belongs to",
            example = "subj456"
    )
    private String subjectId;

    /**
     * Short name or code of the subject.
     * Usually an abbreviated version for display purposes.
     */
    @Schema(
            description = "Short name or code of the subject",
            example = "OOP"
    )
    private String subjectShortName;

    /**
     * Full name of the subject this group belongs to.
     */
    @Schema(
            description = "Full name of the subject this group belongs to",
            example = "Object Oriented Programming"
    )
    private String subjectName;

    /**
     * Number of credits associated with the subject.
     */
    @Schema(
            description = "Number of credits associated with the subject",
            example = "3"
    )
    private Integer subjectCredits;

    /**
     * Academic level of the subject (e.g., 1st semester, 2nd semester, etc.).
     */
    @Schema(
            description = "Academic level of the subject",
            example = "3"
    )
    private Integer subjectLevel;

    /**
     * Total capacity of the associated class session.
     */
    @Schema(
            description = "Total capacity of the associated class session",
            example = "35"
    )
    private Integer sessionCapacity;

    /**
     * Number of students currently enrolled in the associated class session.
     */
    @Schema(
            description = "Number of students currently enrolled in the associated class session",
            example = "28"
    )
    private Integer sessionEnrolledStudents;

    /**
     * Start date and time of the associated class session.
     */
    @Schema(
            description = "Start date and time of the associated class session",
            example = "2025-01-15T08:00:00"
    )
    private LocalDateTime sessionStartDate;

    /**
     * End date and time of the associated class session.
     */
    @Schema(
            description = "End date and time of the associated class session",
            example = "2025-01-15T10:00:00"
    )
    private LocalDateTime sessionEndDate;

    // Group capacity and enrollment information
    /**
     * Maximum number of students allowed in this group.
     * This represents the group's capacity limit.
     */
    @Schema(
            description = "Maximum number of students allowed in the group",
            example = "30"
    )
    private Integer maxStudents;

    /**
     * Current number of students enrolled in this group.
     * This is calculated based on the actual enrollments.
     */
    @Schema(
            description = "Current number of students enrolled in the group",
            example = "25"
    )
    private Integer currentStudents;

    /**
     * Indicates whether the group has reached its maximum capacity.
     * True if currentStudents >= maxStudents.
     */
    @Schema(
            description = "Indicates whether the group has reached its maximum capacity",
            example = "false"
    )
    private Boolean isFull;

    /**
     * Percentage of group capacity currently occupied.
     * Calculated as (currentStudents / maxStudents) * 100.
     */
    @Schema(
            description = "Percentage of group capacity currently occupied",
            example = "83.33"
    )
    private Double occupancyPercentage;

    // Lists of related entity IDs (following PetitionResponseDTO pattern)
    /**
     * List of IDs of students currently enrolled in this group.
     * These are references to Student entities.
     */
    @Schema(
            description = "List of student IDs currently enrolled in the group",
            example = "[\"student123\", \"student456\", \"student789\"]"
    )
    private List<String> enrolledStudentIds;

    /**
     * List of schedule IDs associated with this group.
     * These define when the group meets regularly.
     */
    @Schema(
            description = "List of schedule IDs associated with the group",
            example = "[\"schedule123\", \"schedule456\"]"
    )
    private List<String> scheduleIds;

    /**
     * List of class schedule IDs for specific time slots.
     * These provide detailed scheduling information for the group.
     */
    @Schema(
            description = "List of class schedule IDs for specific time slots",
            example = "[\"classSchedule123\", \"classSchedule456\"]"
    )
    private List<String> classScheduleIds;

    // Metadata and timestamps (following PetitionResponseDTO pattern)
    /**
     * Date and time when the group was created.
     * This timestamp is set automatically when the group is first saved.
     */
    @Schema(
            description = "Timestamp when the group was created",
            example = "2025-01-08T10:30:00"
    )
    private LocalDateTime creationDate;

    /**
     * Date and time when the group was last modified.
     * This timestamp is updated automatically whenever the group is updated.
     */
    @Schema(
            description = "Timestamp when the group was last modified",
            example = "2025-01-08T14:45:00"
    )
    private LocalDateTime modificationDate;

    /**
     * Indicates whether the group is currently active.
     * Inactive groups may be archived or temporarily disabled.
     */
    @Schema(
            description = "Indicates whether the group is currently active",
            example = "true"
    )
    private Boolean isActive;

    
    /**
     * Additional details and metadata about the group.
     * This flexible structure can contain various types of information
     * such as classroom assignments, semester information, group type,
     * special requirements, or any other relevant data.
     * Similar to the details field in PetitionResponseDTO.
     */
    @Schema(
            description = "Map of additional details and metadata about the group. " +
                    "May contain information such as classroom location, semester, " +
                    "group type, special requirements, or other relevant data.",
            example = "{\"classroom\": \"Lab A-301\", \"semester\": \"2025-1\", \"groupType\": \"LABORATORY\", \"specialRequirements\": \"Laptops required\"}"
    )
    private Map<String, Object> details;

    /**
     * History of important events and changes for this group.
     * This provides an audit trail of significant actions performed on the group,
     * similar to the decisionHistory in PetitionResponseDTO.
     * Each entry typically includes a timestamp and description of the event.
     */
    @Schema(
            description = "Complete history of important events and changes for traceability. " +
                    "Each entry represents a significant action or change made to the group.",
            example = "[\"2025-01-08T10:30:00 - Group created by admin\", " +
                    "\"2025-01-09T14:15:00 - Student John Doe enrolled\", " +
                    "\"2025-01-10T09:45:00 - Schedule updated\"]"
    )
    private List<String> eventHistory;

    @Data
        @Schema(description = "Response DTO for subject information")
        public static class SubjectResponseDTO {
        @Schema(description = "ID de la materia", example = "DOSW")
        private String subjectId;
        @Schema(description = "Nombre corto", example = "DOSW")
        private String shortName;
        @Schema(description = "Nombre completo", example = "Desarrollo de Software")
        private String name;
        @Schema(description = "Créditos", example = "4")
        private Integer credits;
        @Schema(description = "Nivel", example = "2")
        private Integer level;
        @Schema(description = "IDs de materias prerequisito", example = "[\"MBDA\", \"POOB\"]")
        private List<String> prerequisiteIds;

        @Schema(description = "Lista de IDs de grupos (ClassSession) asociados a la materia", example = "[\"GRUPO1\", \"GRUPO2\"]")
        private List<String> classSessionIds;
        }

    @Data
    @Schema(description = "Response DTO for professor information")
    public static class ProfessorResponseDTO {
        @Schema(description = "Unique identifier of the professor", example = "1000098653")
        private String professorCode;

        @Schema(description = "Full name of the professor", example = "Juan Perez")
        private String name;

        @Schema(description = "Email address of the professor", example = "juan.perez@mail.escuelaing.edu.co")
        private String mail;

        @Schema(description = "Document number of the professor", example = "123456789")
        private String document;

        private List<String> groupIds;
    }

}