apiVersion: apps/v1
kind: Deployment
metadata:
  name: sirha-api
  namespace: sirha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sirha-api
  template:
    metadata:
      labels:
        app: sirha-api
    spec:
      containers:
        - name: sirha-api
          image: sirha-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-uri
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
